development:
  bucket: postcard-dev.spiralax.com
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
test:
  bucket: postcard-test.spiralax.com
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
production:
  bucket: postcard-pro.spiralax.com
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']