development:
  bucket: ENV['DEV_S3_BUCKET']
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
test:
  bucket: ENV['TEST_S3_BUCKET']
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']
production:
  bucket: ENV['S3_BUCKET']
  access_key_id: ENV['S3_KEY']
  secret_access_key: ENV['S3_SECRET']